# Generated by Django 4.2.4 on 2026-01-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages_text", models.TextField()),
                ("messages_file", models.FileField(upload_to="")),
                ("messages_time", models.DateTimeField(auto_now_add=True)),
                (
                    "messages_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
                (
                    "messages_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.alluser"
                    ),
                ),
            ],
        ),
    ]
