# Generated by Django 4.2.4 on 2026-01-14 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_alter_messages_messages_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
