# Generated by Django 4.2.4 on 2026-01-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0004_group_group_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="messages_file",
            field=models.FileField(blank=True, upload_to="\x0cile"),
        ),
    ]
