# Generated by Django 4.2.4 on 2026-01-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0008_alter_messages_messages_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
