# Generated by Django 4.2.4 on 2026-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0009_alter_group_group_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_member",
            field=models.ManyToManyField(blank=True, to="group.alluser"),
        ),
    ]
