# Generated by Django 4.2.4 on 2026-01-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0010_alter_group_group_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("securemessages_replysource", models.IntegerField(blank=True)),
                ("securemessages_text", models.TextField(blank=True)),
                ("securemessages_file", models.FileField(blank=True, upload_to="")),
                ("securemessages_time", models.DateTimeField(auto_now_add=True)),
                (
                    "securemessages_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.group"
                    ),
                ),
                (
                    "securemessages_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="group.alluser"
                    ),
                ),
            ],
        ),
    ]
