# Generated by Django 4.2.4 on 2026-01-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0011_securemessages"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("securegroup_title", models.CharField(max_length=100, unique=True)),
                ("securegroup_date", models.DateField(auto_now_add=True)),
                (
                    "securegroup_member",
                    models.ManyToManyField(blank=True, to="group.alluser"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="securemessages",
            name="securemessages_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="group.securegroup"
            ),
        ),
    ]
