# Generated by Django 4.2.4 on 2026-01-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0012_securegroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securemessages",
            name="securemessages_replysource",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
