# Generated by Django 4.2.4 on 2026-01-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0013_alter_securemessages_securemessages_replysource"),
    ]

    operations = [
        migrations.AddField(
            model_name="securemessages",
            name="securemessages_member1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="group.securemessages",
            ),
        ),
    ]
