# Generated by Django 4.2.4 on 2026-01-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0014_securemessages_securemessages_member1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="securemessages",
            old_name="securemessages_member1",
            new_name="securemessages_replymessage",
        ),
    ]
