# Generated by Django 4.2.4 on 2026-01-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "group",
            "0015_rename_securemessages_member1_securemessages_securemessages_replymessage",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securemessages",
            name="securemessages_replysource",
        ),
    ]
