# Generated by Django 4.2.4 on 2026-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0016_remove_securemessages_securemessages_replysource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securemessages",
            name="securemessages_file",
            field=models.FileField(blank=True, upload_to="secure/"),
        ),
    ]
